# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63234136f554de2abc5bcbe9adaba96ef70ce467265dad7b7775a173c55ec83bdba0d1f2e0a673ed9f1bbdb703f418b37aecf330ad461f7de8fe68bea7911bc3

test:
  secret_key_base: 3152bff595725b45165f05d5647577b2fc691243d2f41ac34280d2e05ac3d998111fa985a3b8e0c6ca508ceffc7be82e4f5ff84c8b49ca6f2ab184cf7a49bac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
